#!/usr/bin/python
from sys import argv
with open(argv[1]) as a:a=a.read()
b=a.find("APE""TAGEX")
if b == -1:pass
elif b+b<len(a):
	c=a.find("APE""TAGEX",b+1)
	if c!=-1:open(argv[1],"w").write(a[:b]+a[c+72:])
	else:print("%s %c"%(argv[1],b))
else:open(argv[1],"w").write(a[:b])
