#!/bin/sh
t=`tempfile`
eval `python -c 'from sys import argv
argv=[{
"r":"|sort -R",
"s":"|sort",
"m":"~/Musique/",
"p":"mplayer"}.get(c,c) for c in argv[1:] if c]
p=""
for c in range(len(argv)-3,-1,-1):
	if argv[c]==",":argv[c:c+3]=argv[c+1]+argv[c+2]
while c<len(argv):
	if argv[c].isdigit():argv[c:c+2]=(argv[c+1],)*int(argv[c])
	elif argv[c][0]=="|":p+=argv.pop(c)
	else:c+=1
print("find "+" ".join(argv[1:])+p+">$t;exec xargs -a $t "+argv[0])' $@`