#!/usr/bin/python
from pyglet import window,clock,app
from subprocess import Popen,PIPE
from sys import argv
S=window.get_platform().get_default_display().get_default_screen()
W=window.Window(S.width,50,style="borderless",vsync=0,visible=0)
C=clock.ClockDisplay(font.load(name="Monospace",size=32),color=(1.,1.,1.,1.))
A=[app.exit]+[W.flip]*int(argv[1])
def draw(t):
	W.clear()
	C.format=Popen(argv[3:],stdout=PIPE).stdout.read()[:-1]
	C.update_text()
	C.draw()
	return A.pop()()
clock.schedule_interval(draw,float(argv[2]))
W.set_visible(1)
W.set_location(0,S.height-100>>1)
W.on_draw=W.dispatch_events
app.run()
