#!/bin/sh
if [ $# -eq 0 ]
then exec mpv -shuffle ~/m/*/*
elif [ -d "$1" -o -f "$1" ]
then exec find "$@" -type f -exec mpv -shuffle {} \+
else t=`mktemp`
if [ "$1" = p ]
then CM=mpv
else CM="$1"
fi
shift
for a
do
if [ "${a:0:1}" = \| ]
then SH="$SH$a"
elif [ "$a" = r ]
then SH="$SH|sort -Rz"
elif [ "$a" = s ]
then SH="$SH|sort -z"
else FN="$FN "`printf %q "$a"`
fi
done
eval "find $FN -type f -print0$SH>\$t;exec xargs -0a \$t $CM"
exec rm $t
fi
